#main:
#   resource: "@MainBundle/Resources/config/routing.yml"
#    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

add:
    path:      /add
    defaults:  { _controller: MainBundle:Main:add }